version: '3.1'

services:
  db:
    image: postgres:12.1
    restart: always
    env_file: ./.env
    ports:
      - 5433:5432
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    external:
      name: my-network
