FROM rust:1.41 as builder

# update container
RUN apt-get update && apt-get install -y libpq5

WORKDIR /usr/src/

# create blank project
RUN USER=root cargo new splitterrust_server

# Install deps, this will cache them so we can
# build the container faster for development.
COPY Cargo.toml /usr/src/splitterrust_server/

WORKDIR /usr/src/splitterrust_server

RUN cargo build

# Now copy source files and install the application.
COPY . .

# This is the actual build.
RUN cargo build

EXPOSE 8088

CMD ["splitterrust_server"]
