version: '3.1'

services:
  db:
    image: postgres:12.1
    restart: always
    ports:
      - 5433:5432
    env_file: .env_docker

  server:
    image: splitterrust_server
    restart: always
    ports:
        - 8088:8088
    env_file: .env_docker

  discord:
    image: splitterrust_discord
    env_file: .env_docker

