version: '3.1'

services:
  db:
    image: postgres:12.1
    restart: always
    env_file: .env_docker
    ports:
      - 5433:5432
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:80
    networks:
      - default
    env_file: .env_docker

networks:
  default:
    external:
      name: my-network
